CREATE TABLE ProductCategory(Id VARCHAR(255) PRIMARY KEY, TITLE VARCHAR(255),
ProductId VARCHAR(255) FOREIGN KEY REFERENCES Products(Id) NOT NULL,
CategoriesId VARCHAR(255) FOREIGN KEY REFERENCES Categories(Id) NOT NULL,);